DomiZadatakWin/Models/ErrorViewModel.cs
namespace DomiZadatakWin.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DomiZadatakWin/Models/Partner.cs
using System.ComponentModel.DataAnnotations;

namespace DomiZadatakWin.Models
{
    public class Partner
    {
        [Key]
        public int Id { get; set; }
        
        [Required(ErrorMessage = "Ime je obavezno")]
        [StringLength(255, ErrorMessage = "FirstName mora biti između 2 i 255 znakova")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Prezime je obavezno")]
        [StringLength(255, ErrorMessage = "LastName mora biti između 2 i 255 znakova")]

        public string LastName { get; set; }
        public string Address { get; set; }

        [Required(ErrorMessage = "Partner Broj je obavezan")]
        [StringLength(20, MinimumLength = 20, ErrorMessage = "Partner Broj mora imati točno 20 znakova")]
        public string PartnerNumber { get; set; }

        [RegularExpression(@"\b\d{11}\b", ErrorMessage = "Hrvatski PIN mora biti 11 znamenki")]
        public string CroatianPIN { get; set; }

        [Required(ErrorMessage = "PartnerTypeId je obavezan")]
        [Range(1, 2, ErrorMessage = "PartnerTypeId mora biti 1 ili 2")]
        public int PartnerTypeId { get; set; }
        public DateTime CreatedAtUtc { get; set; }

        [Required(ErrorMessage = "CreateByUser je obavezan")]
        [StringLength(255, ErrorMessage = "CreateByUser ne smije biti duži od 255 znakova")]
        public string CreateByUser { get; set; }
        

        public bool? IsForeign { get; set; }

        [StringLength(20, MinimumLength = 10, ErrorMessage = "ExternalCode mora biti između 10 i 20 znakova")]
        public string ExternalCode { get; set; }

        [Required(ErrorMessage = "Gender je obavezan")]
        [RegularExpression("[M|F|N]", ErrorMessage = "Gender mora biti M, F ili N")]
        public char Gender { get; set; }

        // Navigation property for policies
        public List<Policy> Policies { get; set; }
    }
}

DomiZadatakWin/Models/Policy.cs
namespace DomiZadatakWin.Models
{
    public class Policy
    {
        public int Id { get; set; }
        public string PolicyNumber { get; set; }
        public decimal PolicyAmount { get; set; }

        // Foreign key za Partnera
        public int PartnerId { get; set; }
        public Partner Partner { get; set; }
    }
}

DomiZadatakWin/Controllers/HomeController.cs
using DomiZadatakWin.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace DomiZadatakWin.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DomiZadatakWin/Controllers/PartnerController.cs
using DomiZadatakWin.Data;
using DomiZadatakWin.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DomiZadatakWin.Controllers
{
    public class PartnerController : Controller
    {
        private readonly ApplicationDbContext _db;

        public PartnerController(ApplicationDbContext db)
        {
            _db = db;
        }


        public IActionResult Index()
        {

            List<Partner> objPartnerlList = _db.Partners.ToList();
            return View(objPartnerlList);
            

        }

        public IActionResult Create()
        {
            return View();
    
        }

        [HttpPost]
        
        public IActionResult Create(Partner obj)
        {
           // if (ModelState.IsValid)
           // {
                _db.Partners.Add(obj);
                _db.SaveChanges();

                TempData["success"] = "Partner je uspješno kreiran!";

                return RedirectToAction("Index");

           // }

            //return View();

        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            Partner? partnerFromDb = _db.Partners.Find(id);
            if (partnerFromDb == null)
            {
                return NotFound();
            }
            return View(partnerFromDb);
        }

        [HttpPost]
        public IActionResult Edit(Partner obj)
        {
            //if (ModelState.IsValid)
            //{
                _db.Partners.Update(obj);
                _db.SaveChanges();

                TempData["success"] = "Partner je uspješno izmijenjen!";

                return RedirectToAction("Index");

            }

            //return View();

        //}

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            Partner? partnerFromDb = _db.Partners.Find(id);
            if (partnerFromDb == null)
            {
                return NotFound();
            }
            return View(partnerFromDb);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePOST(int? id)

        {
            Partner? obj = _db.Partners.Find(id);

            if (obj == null)
            {
                return NotFound();
            }

            _db.Partners.Remove(obj);
            _db.SaveChanges();

            TempData["success"] = "Partner je uspješno uklonjen";

            return RedirectToAction("Index");

        }


        public IActionResult Details(int id)
        {
            Partner? partnerFromDb = _db.Partners.Find(id);

            if (partnerFromDb == null)
            {
                return NotFound();
            }

            return View(partnerFromDb);
        }

    }


}

DomiZadatakWin/Controllers/PolicyController.cs
using DomiZadatakWin.Data;
using DomiZadatakWin.Models;
using Microsoft.AspNetCore.Mvc;

namespace DomiZadatakWin.Controllers
{
    public class PolicyController : Controller
    {
        private readonly ApplicationDbContext _db;

        public PolicyController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index(int? id)
        {

            List<Policy> objPolicyList = _db.Policies.ToList();
            return View(objPolicyList);
        }


        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]

        public IActionResult Create(Policy obj)
        {
            if (ModelState.IsValid)
            {
                _db.Policies.Add(obj);
                _db.SaveChanges();

                TempData["success"] = "Polica je uspješno kreirana!";

                return RedirectToAction("Index");

            }

            return View();

        }
    }
}

DomiZadatakWin/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

DomiZadatakWin/Views/Partner/Create.cshtml
@model Partner

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Kreiranje Partnera</h2>
            <hr />
        </div>
        @*  <div asp-validation-summary="All"></div> *@
        <div class="mb-2 row p-1">
            <label asp-for="FirstName" class="p-0"></label>
            <input asp-for="FirstName" class="form-control" />
            <span asp-validation-for="FirstName" class="text-danger"></span>
        </div>
        <div class="mb-2 row p-1">
            <label asp-for="LastName" class="p-0"></label>
            <input asp-for="LastName" class="form-control" />
            <span asp-validation-for="LastName" class="text-danger"></span>
        </div>
        <div class="mb-2 row p-1">
            <label asp-for="Address" class="p-0"></label>
            <input asp-for="Address" class="form-control" />
            <span asp-validation-for="Address" class="text-danger"></span>
        </div>
        <div class="mb-2 row p-1">
            <label asp-for="PartnerNumber" class="p-0"></label>
            <input asp-for="PartnerNumber" class="form-control" />
            <span asp-validation-for="PartnerNumber" class="text-danger"></span>
        </div>
        <div class="mb-2 row p-1">
            <label asp-for="CroatianPIN" class="p-0"></label>
            <input asp-for="CroatianPIN" class="form-control" />
            <span asp-validation-for="CroatianPIN" class="text-danger"></span>
        </div>
        <div class="mb-2 row p-1">
            <label asp-for="PartnerTypeId" class="p-0"></label>
            <input asp-for="PartnerTypeId" class="form-control" />
            <span asp-validation-for="PartnerTypeId" class="text-danger"></span>
        </div>
        <div class="mb-2 row p-1">
            <label asp-for="CreatedAtUtc" class="p-0"></label>
            <input asp-for="CreatedAtUtc" class="form-control" />
            <span asp-validation-for="CreatedAtUtc" class="text-danger"></span>
        </div>
        <div class="mb-2 row p-1">
            <label asp-for="CreateByUser" class="p-0"></label>
            <input asp-for="CreateByUser" class="form-control" />
            <span asp-validation-for="CreateByUser" class="text-danger"></span>
         </div>
         <div class="mb-2 row p-1">
                <label asp-for="IsForeign" class="p-0"></label>
                <input asp-for="IsForeign" class="form-control" data-val="false" />
                <span asp-validation-for="IsForeign" class="text-danger"></span>
        </div>
        <div class="mb-2 row p-1">
            <label asp-for="ExternalCode" class="p-0"></label>
            <input asp-for="ExternalCode" class="form-control" />
            <span asp-validation-for="ExternalCode" class="text-danger"></span>
        </div>
        <div class="mb-2 row p-1">
            <label asp-for="Gender" class="p-0"></label>
            <input asp-for="Gender" class="form-control" />
            <span asp-validation-for="Gender" class="text-danger"></span>
        </div>
        <div class="row">
            <div class="col-6">
                <button type="submit" class="btn btn-primary form-control">Kreiraj i Spremi</button>
            </div>
            <div class="col-6">
                <a asp-controller="Partner" asp-action="Index" class="btn btn-outline-secondary border form-control">
                    Vrati se nazad
                </a>
            </div>
        </div>

    </div>
</form>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />

        <script>
            $(document).ready(function () {
                
                var currentLocalTime = new Date().toLocaleString();
                $("#CreatedAtUtc").val(currentLocalTime);
            });
        </script>

    }

}

DomiZadatakWin/Views/Partner/Delete.cshtml
@model Partner

<form method="post">
    <input asp-for="Id" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Uređivanje Partnera</h2>
            <hr />
        </div>
        @*  <div asp-validation-summary="All"></div> *@
        <div class="mb-2 row p-1">
            <label asp-for="Id" class="p-0"></label>
            <input asp-for="Id" disabled class="form-control" />
            
        </div>
        <div class="mb-2 row p-1">
            <label asp-for="FirstName" class="p-0"></label>
            <input asp-for="FirstName" disabled class="form-control" />
            
        </div>
        <div class="mb-2 row p-1">
            <label asp-for="LastName" class="p-0"></label>
            <input asp-for="LastName" disabled class="form-control" />
            
        </div>
        <div class="mb-2 row p-1">
            <label asp-for="Address" class="p-0"></label>
            <input asp-for="Address" disabled class="form-control" />
            
        </div>
        <div class="mb-2 row p-1">
            <label asp-for="PartnerNumber" class="p-0"></label>
            <input asp-for="PartnerNumber" disabled class="form-control" />
            
        </div>
        <div class="mb-2 row p-1">
            <label asp-for="CroatianPIN" class="p-0"></label>
            <input asp-for="CroatianPIN" disabled class="form-control" />
            
        </div>
        <div class="mb-2 row p-1">
            <label asp-for="PartnerTypeId" class="p-0"></label>
            <input asp-for="PartnerTypeId" disabled class="form-control" />
            
        </div>
        <div class="mb-2 row p-1">
            <label asp-for="CreatedAtUtc" class="p-0"></label>
            <input asp-for="CreatedAtUtc" disabled class="form-control" />
            
        </div>
        <div class="mb-2 row p-1">
            <label asp-for="CreateByUser" class="p-0"></label>
            <input asp-for="CreateByUser" disabled class="form-control" />
            
        </div>
        <div class="mb-2 row p-1">
            <label asp-for="IsForeign" class="p-0"></label>
            <input asp-for="IsForeign" disabled class="form-control" />
            
        </div>
        <div class="mb-2 row p-1">
            <label asp-for="ExternalCode" class="p-0"></label>
            <input asp-for="ExternalCode" disabled class="form-control" />
           
        </div>
        <div class="mb-2 row p-1">
            <label asp-for="Gender" class="p-0"></label>
            <input asp-for="Gender" disabled class="form-control" />
            <span asp-validation-for="Gender" class="text-danger"></span>
        </div>
        <div class="row">
            <div class="col-6">
                <button type="submit" class="btn btn-danger form-control">Obriši</button>
            </div>
            <div class="col-6">
                <a asp-controller="Partner" asp-action="Index" class="btn btn-outline-secondary border form-control">
                    Vrati se nazad
                </a>
            </div>
        </div>

    </div>
</form>

DomiZadatakWin/Views/Partner/Details.cshtml
@model Partner

<form method="post">
    <input asp-for="Id" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Detalji Partnera</h2>
            <hr />
        </div>
        @*  <div asp-validation-summary="All"></div> *@
        <div class="mb-2 row p-1">
            <label asp-for="Id" class="p-0"></label>
            <input asp-for="Id" disabled class="form-control" />

        </div>
        <div class="mb-2 row p-1">
            <label asp-for="FirstName" class="p-0"></label>
            <input asp-for="FirstName" disabled class="form-control" />

        </div>
        <div class="mb-2 row p-1">
            <label asp-for="LastName" class="p-0"></label>
            <input asp-for="LastName" disabled class="form-control" />

        </div>
        <div class="mb-2 row p-1">
            <label asp-for="Address" class="p-0"></label>
            <input asp-for="Address" disabled class="form-control" />

        </div>
        <div class="mb-2 row p-1">
            <label asp-for="PartnerNumber" class="p-0"></label>
            <input asp-for="PartnerNumber" disabled class="form-control" />

        </div>
        <div class="mb-2 row p-1">
            <label asp-for="CroatianPIN" class="p-0"></label>
            <input asp-for="CroatianPIN" disabled class="form-control" />

        </div>
        <div class="mb-2 row p-1">
            <label asp-for="PartnerTypeId" class="p-0"></label>
            <input asp-for="PartnerTypeId" disabled class="form-control" />

        </div>
        <div class="mb-2 row p-1">
            <label asp-for="CreatedAtUtc" class="p-0"></label>
            <input asp-for="CreatedAtUtc" disabled class="form-control" />

        </div>
        <div class="mb-2 row p-1">
            <label asp-for="CreateByUser" class="p-0"></label>
            <input asp-for="CreateByUser" disabled class="form-control" />

        </div>
        <div class="mb-2 row p-1">
            <label asp-for="IsForeign" class="p-0"></label>
            <input asp-for="IsForeign" disabled class="form-control" />

        </div>
        <div class="mb-2 row p-1">
            <label asp-for="ExternalCode" class="p-0"></label>
            <input asp-for="ExternalCode" disabled class="form-control" />

        </div>
        <div class="mb-2 row p-1">
            <label asp-for="Gender" class="p-0"></label>
            <input asp-for="Gender" disabled class="form-control" />
            <span asp-validation-for="Gender" class="text-danger"></span>
        </div>
        <div class="row">
            <div class="col-12">
                <a asp-controller="Partner" asp-action="Index" class="btn btn-outline-secondary border form-control">
                    Vrati se nazad
                </a>
            </div>
        </div>

    </div>
</form>

DomiZadatakWin/Views/Partner/Edit.cshtml
@model Partner

<form method="post">
    <input asp-for="Id" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Uređivanje Partnera</h2>
            <hr />
        </div>
        @*  <div asp-validation-summary="All"></div> *@
        <div class="mb-2 row p-1">
            <label asp-for="FirstName" class="p-0"></label>
            <input asp-for="FirstName" class="form-control" />
            <span asp-validation-for="FirstName" class="text-danger"></span>
        </div>
        <div class="mb-2 row p-1">
            <label asp-for="LastName" class="p-0"></label>
            <input asp-for="LastName" class="form-control" />
            <span asp-validation-for="LastName" class="text-danger"></span>
        </div>
        <div class="mb-2 row p-1">
            <label asp-for="Address" class="p-0"></label>
            <input asp-for="Address" class="form-control" />
            <span asp-validation-for="Address" class="text-danger"></span>
        </div>
        <div class="mb-2 row p-1">
            <label asp-for="PartnerNumber" class="p-0"></label>
            <input asp-for="PartnerNumber" class="form-control" />
            <span asp-validation-for="PartnerNumber" class="text-danger"></span>
        </div>
        <div class="mb-2 row p-1">
            <label asp-for="CroatianPIN" class="p-0"></label>
            <input asp-for="CroatianPIN" class="form-control" />
            <span asp-validation-for="CroatianPIN" class="text-danger"></span>
        </div>
        <div class="mb-2 row p-1">
            <label asp-for="PartnerTypeId" class="p-0"></label>
            <input asp-for="PartnerTypeId" class="form-control" />
            <span asp-validation-for="PartnerTypeId" class="text-danger"></span>
        </div>
        <div class="mb-2 row p-1">
            <label asp-for="CreatedAtUtc" class="p-0"></label>
            <input asp-for="CreatedAtUtc" class="form-control" />
            <span asp-validation-for="CreatedAtUtc" class="text-danger"></span>
        </div>
        <div class="mb-2 row p-1">
            <label asp-for="CreateByUser" class="p-0"></label>
            <input asp-for="CreateByUser" class="form-control" />
            <span asp-validation-for="CreateByUser" class="text-danger"></span>
        </div>
        <div class="mb-2 row p-1">
            <label asp-for="IsForeign" class="p-0"></label>
            <input asp-for="IsForeign" class="form-control" data-val="false" />
            <span asp-validation-for="IsForeign" class="text-danger"></span> 
        </div>
        <div class="mb-2 row p-1">
            <label asp-for="ExternalCode" class="p-0"></label>
            <input asp-for="ExternalCode" class="form-control" />
            <span asp-validation-for="ExternalCode" class="text-danger"></span>
        </div>
        <div class="mb-2 row p-1">
            <label asp-for="Gender" class="p-0"></label>
            <input asp-for="Gender" class="form-control" />
            <span asp-validation-for="Gender" class="text-danger"></span>
        </div>
        <div class="row">
            <div class="col-6">
                <button type="submit" class="btn btn-primary form-control">Ažuriraj</button>
            </div>
            <div class="col-6">
                <a asp-controller="Partner" asp-action="Index" class="btn btn-outline-secondary border form-control">
                    Vrati se nazad
                </a>
            </div>
        </div>

    </div>
</form>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />

    }

}

DomiZadatakWin/Views/Partner/Index.cshtml
@model List<Partner>

<div class="container">
    <div class="row pt-4 pb-3">
        <div class="col-6">
            <h2 class="text-primary">
                Lista svih partnera osiguravajućeg društva
            </h2>

        </div>
        <div class="col-6 text-end">
            <a asp-controller="Partner" asp-action="Create" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i> Kreiraj Partnera
            </a>
        </div>
    </div>

    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>
                    FullName
                </th>
                <th>
                    PartnerNumber
                </th>
                <th>
                    PartnerTypeId
                </th>
                <th>
                    CreatedAtUtc
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model.OrderBy(u => u.CreatedAtUtc))
            {
                <tr>
                    <td>@($"{obj.FirstName} {obj.LastName}")</td>
                    <td>@obj.PartnerNumber</td>
                    <td>@obj.PartnerTypeId</td>
                    <td>@obj.CreatedAtUtc</td>

                    <td>
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="Partner" asp-action="Details" asp-route-id="@obj.Id" class="btn btn-success mx-2">
                                <i class="bi bi-info-lg"></i> Details
                            </a>
                            <a asp-controller="Policy" asp-action="Index" class="btn btn-info mx-2">
                                <i class="bi bi-info-lg"></i> Details Policy
                            </a>
                            <a asp-controller="Partner" asp-action="Edit" asp-route-id="@obj.Id" class="btn btn-primary mx-2">
                                <i class="bi bi-pencil-square"></i> Edit
                            </a>
                            <a asp-controller="Partner" asp-action="Delete" asp-route-id="@obj.Id" class="btn btn-danger mx-2">
                                <i class="bi bi-trash-fill"></i> Delete
                            </a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

DomiZadatakWin/Views/Policy/Create.cshtml
@model Policy

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Kreiranje Police</h2>
            <hr />
        </div>
        @*  <div asp-validation-summary="All"></div> *@
        <div class="mb-2 row p-1">
            <label asp-for="PolicyNumber" class="p-0"></label>
            <input asp-for="PolicyNumber" class="form-control" />
            <span asp-validation-for="PolicyNumber" class="text-danger"></span>
        </div>
        <div class="mb-2 row p-1">
            <label asp-for="PolicyAmount" class="p-0"></label>
            <input asp-for="PolicyAmount" class="form-control" />
            <span asp-validation-for="PolicyAmount" class="text-danger"></span>
        </div>
        <div class="row">
            <div class="col-6">
                <button type="submit" class="btn btn-primary form-control">Kreiraj i Spremi</button>
            </div>
            <div class="col-6">
                <a asp-controller="Policy" asp-action="Index" class="btn btn-outline-secondary border form-control">
                    Vrati se nazad na police
                </a>
            </div>
            <div class="col-12 pt-2">
                <a asp-controller="Partner" asp-action="Index" class="btn btn-outline-secondary border form-control">
                    Vrati se nazad na početnu stranicu
                </a>
            </div>
        </div>

    </div>
</form>

DomiZadatakWin/Views/Policy/Index.cshtml
@model  List<Policy>

<div class="container">
    <div class="row pt-4 pb-3">
        <div class="col-6">
            <h2 class="text-primary">
                Lista Polica
            </h2>

        </div>
        <div class="col-6 text-end">
            <a asp-controller="Policy" asp-action="Create" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i> Kreiraj Policu
            </a>
        </div>
    </div>

    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>
                    Policy Number
                </th>
                <th>
                    Amount
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model)
            {
                <tr>
                    <td>@obj.PolicyNumber</td>
                    <td>@obj.PolicyAmount</td>
                    <td>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div

DomiZadatakWin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DomiZadatakWin</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DomiZadatakWin.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-expand-lg bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-dark" asp-area="" asp-controller="Partner" asp-action="Index">
                    <img src="~/images/logo.png" style="width:60px" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                       @*  <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li> *@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Partner" asp-action="Index">Lista Partnera</a>
                        </li>
                       @*  <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Partner" asp-action="Create">Unos Partnera</a>
                        <li class="nav-item"> *@
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div id="particles-js"></div>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>
    <div id="particles-js"></div>  
    <footer class="border-top footer bg-primary text-white text-center mt-5">
        <div id="footer" class="d-flex justify-content-between align-items-center p-1">
            <div id="copyright">
                <p>Created by &#64 Domagoj Petrec  <i class="bi bi-emoji-sunglasses-fill"></i> </p>
            </div>
            <div id="social-icons" class="d-flex gap-2">
                <a href="https://www.linkedin.com/in/domagoj-petrec-08369b262/" class="social-icon"><i class="bi bi-linkedin"></i></a>
                <a href="https://www.instagram.com/domagoj.petrec/" class="social-icon"><i class="bi bi-instagram"></i></a>
                <a href="https://github.com/domic98" class="social-icon"><i class="bi bi-github"></i></a>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="~/js/particles.js"></script>
    <script src="https://cdn.jsdelivr.net/particles.js/2.0.0/particles.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

DomiZadatakWin/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}

@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>

}